---
title: "Data Cleaning"
author: "Ria Pinjani, Christina Ho, Tim Chou"
date: "11/17/2019"
output: pdf_document
---

### Install required packages 

```{r}
# install.packages('jsonlite')
# library(jsonlite)
# require(lubridate)
```


### Variables description for business.json

```

{
    // string, 22 character unique string business id
    "business_id": "tnhfDv5Il8EaGSXZGiuQGg",

    // string, the business's name
    "name": "Garaje",

    // string, the full address of the business
    "address": "475 3rd St",

    // string, the city
    "city": "San Francisco",

    // string, 2 character state code, if applicable
    "state": "CA",

    // string, the postal code
    "postal code": "94107",

    // float, latitude
    "latitude": 37.7817529521,

    // float, longitude
    "longitude": -122.39612197,

    // float, star rating, rounded to half-stars
    "stars": 4.5,

    // integer, number of reviews
    "review_count": 1198,

    // integer, 0 or 1 for closed or open, respectively
    "is_open": 1,

    // object, business attributes to values. note: some attribute values might be objects
    "attributes": {
        "RestaurantsTakeOut": true,
        "BusinessParking": {
            "garage": false,
            "street": true,
            "validated": false,
            "lot": false,
            "valet": false
        },
    },

    // an array of strings of business categories
    "categories": [
        "Mexican",
        "Burgers",
        "Gastropubs"
    ],

    // an object of key day to value hours, hours are using a 24hr clock
    "hours": {
        "Monday": "10:00-21:00",
        "Tuesday": "10:00-21:00",
        "Friday": "10:00-21:00",
        "Wednesday": "10:00-21:00",
        "Thursday": "10:00-21:00",
        "Sunday": "11:00-18:00",
        "Saturday": "10:00-21:00"
    }
}

```

### Variables description for user.json

1,637,138 users

```
{
    // string, 22 character unique user id, maps to the user in user.json
    "user_id": "Ha3iJu77CxlrFm-vQRs_8g",

    // string, the user's first name
    "name": "Sebastien",

    // integer, the number of reviews they've written
    "review_count": 56,

    // string, when the user joined Yelp, formatted like YYYY-MM-DD
    "yelping_since": "2011-01-01",

    // array of strings, an array of the user's friend as user_ids
    "friends": [
        "wqoXYLWmpkEH0YvTmHBsJQ",
        "KUXLLiJGrjtSsapmxmpvTA",
        "6e9rJKQC3n0RSKyHLViL-Q"
    ],

    // integer, number of useful votes sent by the user
    "useful": 21,

    // integer, number of funny votes sent by the user
    "funny": 88,

    // integer, number of cool votes sent by the user
    "cool": 15,

    // integer, number of fans the user has
    "fans": 1032,

    // array of integers, the years the user was elite
    "elite": [
        2012,
        2013
    ],

    // float, average rating of all reviews
    "average_stars": 4.31,

    // integer, number of hot compliments received by the user
    "compliment_hot": 339,

    // integer, number of more compliments received by the user
    "compliment_more": 668,

    // integer, number of profile compliments received by the user
    "compliment_profile": 42,

    // integer, number of cute compliments received by the user
    "compliment_cute": 62,

    // integer, number of list compliments received by the user
    "compliment_list": 37,

    // integer, number of note compliments received by the user
    "compliment_note": 356,

    // integer, number of plain compliments received by the user
    "compliment_plain": 68,

    // integer, number of cool compliments received by the user
    "compliment_cool": 91,

    // integer, number of funny compliments received by the user
    "compliment_funny": 99,

    // integer, number of writer compliments received by the user
    "compliment_writer": 95,

    // integer, number of photo compliments received by the user
    "compliment_photos": 50
}
```


### Variable desciption for review.json

```

{
    // string, 22 character unique review id
    "review_id": "zdSx_SD6obEhz9VrW9uAWA",

    // string, 22 character unique user id, maps to the user in user.json
    "user_id": "Ha3iJu77CxlrFm-vQRs_8g",

    // string, 22 character business id, maps to business in business.json
    "business_id": "tnhfDv5Il8EaGSXZGiuQGg",

    // integer, star rating
    "stars": 4,

    // string, date formatted YYYY-MM-DD
    "date": "2016-03-09",

    // string, the review itself
    "text": "Great place to hang out after work: the prices are decent, and the ambience is fun. It's a bit loud, but very lively. The staff is friendly, and the food is good. They have a good selection of drinks.",

    // integer, number of useful votes received
    "useful": 0,

    // integer, number of funny votes received
    "funny": 0,

    // integer, number of cool votes received
    "cool": 0
}

```





Read in all the data for review, user and business


```{r}

# user = stream_in(file('data/user.json')) 
# user = data.frame(user)

# review = stream_in(file('data/review.json')) 
# review = data.frame(review)

# business = stream_in(file('data/business.json')) 
# business = data.frame(business)
```

Subset business data for only businesses that contain the word restaurant in the column categories

```{r}
# restaurant <- business[c(grep("Restaurant",business$categories), grep("Restaurants",business$categories)),]
```

?

```{r}
# restaurant_user_review <- inner_join(restaurant,user_review, by= "business_id")
```

?

```{r}
# review_business <- merge(review, restaurant[, c("business_id", "review_count", "stars", "city", "state", "address")], by = "business_id", all = T)


```


```{r}
# Randomly choose 1000 restaurants

samp <- sample(nrow(restaurant),1000)
restaurant_data = restaurant[samp,]
```


Read in the saved csv file

```{r}

restaurant_data = read_csv('data/restaurant_data.csv')

```



```{r}
# Select rows from the data set reviews for which business id matches those in restaraunt_data

id = unique(restaurant_data$business_id)
review_chosen <- review[review$business_id %in% id,]

# Filter for only most recent 4 years of reviews
review_dat = review_chosen %>% filter(year(date) %in% c(2015, 2016, 2017, 2018))

# Select rows from the data set user for which user id matches those in review_dat

user_id = unique(review_dat$user_id)
user_chosen <- user[user$user_id %in% user_id,]

# Merge User information with Review information
review_final = merge(review_dat, user_chosen[, c("user_id", "review_count", "yelping_since", "average_stars", "elite", "fans", "average_stars")], by = "user_id", all = T)

final = merge(review_final, restaurant_data[, c("business_id", "name", "city", "state", "stars")], by = "business_id", all = T)
```


Read in the saved csv file



```{r}
review_final <- read_csv('data/review_final.csv')
final <- read_csv('data/final.csv')
```






